repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.5.4
      hooks:
          # Run the linter.
          - id: ruff
            args: [--fix]
          # Run the formatter.
          - id: ruff-format
    - repo: local
      hooks:
          - id: pytest
            name: pytest
            entry: make test
            language: python
            types: [python]
            pass_filenames: false
