name: ying

packages:
    - apps/**
    - packages/**

ide:
    intellij: false

scripts:
    analyze:
        exec: dart analyze .

    format:
        exec: dart format .

    test:
        exec: dart test .

    test-with-coverage:
        exec: dart pub global run coverage:test_with_coverage --function-coverage --branch-coverage

    format-ci:
        exec: dart format --output=none --set-exit-if-changed .

    ci:
        exec: melos run format-ci && melos run analyze && melos run test
