name: Code coverage

on:
    push:
    pull_request:
        branches: ['master']

permissions:
    contents: read

jobs:
    code-coverage:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ['3.12']

        steps:
            - uses: actions/checkout@v4
            - uses: dart-lang/setup-dart@v1
            - run: dart pub global activate melos
            - run: dart pub global activate coverage
            - run: melos bootstrap
            - run: melos run test-with-coverage
            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v4
              with:
                  disable_search: true
                  files: './packages/ying-shared/coverage/lcov.info'
                  verbose: true
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
