name: Code quality

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']

permissions:
    contents: read

jobs:
    code-quality:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ['3.12']

        steps:
            - uses: actions/checkout@v4
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v3
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip poetry
                  poetry install
            - name: Run tests and check code style
              run: make ci
            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v4
              with:
                disable_search: true
                file: "./coverage.xml"
                verbose: true
              env:
                CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
