name: Tests

on:
    push:
    pull_request:
        branches: [master]

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: dart-lang/setup-dart@v1
            - run: dart pub get
            - run: dart run melos bootstrap
            - run: dart run melos ci
